# Generated by Django 4.1.5 on 2023-01-24 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Noticias',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('encabezado', models.CharField(max_length=1000)),
                ('texto', models.CharField(max_length=10000)),
                ('comentario', models.CharField(max_length=10000)),
                ('imagen', models.ImageField(upload_to='noticas/', verbose_name='Imagen de portada')),
            ],
        ),
    ]
