# Generated by Django 3.2.16 on 2023-01-26 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicos', '0005_contacto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portada',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('portada', models.CharField(max_length=100)),
                ('imagen', models.ImageField(upload_to='seguros/', verbose_name='Imagen de Perfil')),
            ],
        ),
        migrations.CreateModel(
            name='Seguros',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('seguro', models.CharField(max_length=100)),
                ('imagen', models.ImageField(upload_to='seguros/', verbose_name='Imagen de Perfil')),
            ],
        ),
    ]
