# Generated by Django 3.0.6 on 2023-05-20 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medicos', '0006_portada_seguros'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sucursal', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='medico',
            name='sub_especialidad',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medico',
            name='sucursal',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='medicos.Sucursal'),
            preserve_default=False,
        ),
    ]
